version: "3.8" # Or a suitable version for your setup

services:
    lyricalysisui-frontend:
        build:
            context: /LyricalysisUI
            dockerfile: Dockerfile
        ports:
            - "5000:5000" # Replace 3000 with your frontend's port
        depends_on:
            - lyricalysisui-backend

    lyricalysisui-backend:
        build:
            context: /LyricalysisUI/Backend
            dockerfile: Dockerfile
        ports:
            - "5173:5173" # Replace 5000 with your backend's port
        depends_on:
            - solr

    solr:
        build:
            context: /SolrDocker/lyrics-prod
            dockerfile: Dockerfile
        ports:
            - "8983:8983" # Expose Solr's standard port
