version: "3.8"

services:
    lyricalysisui-frontend:
        build:
            context: ./LyricalysisUI
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - lyricalysisui-backend

    lyricalysisui-backend:
        build:
            context: ./LyricalysisUI/Backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        depends_on:
            - solr

    solr:
        build:
            context: ./SolrDocker/lyrics-prod
            dockerfile: Dockerfile
        ports:
            - "8983:8983"
